sudo: false

cache:
  apt: true
  ccache: true

language: generic
#os: osx
matrix:
  include:
    - os: linux
      env:
        - COMPILER_NAME=gcc
        - CXX=g++-5
        - CC=gcc-5
      dist: trusty
      addons:
        apt:
          packages:
            - g++-5
            - cmake
            - cmake-data
            - python3
            - python
          sources: &sources
            #- llvm-toolchain-precise-3.8
            #- george-edison55-precise-backports
            - ubuntu-toolchain-r-test
#    - os: linux
#      env:
#        - COMPILER_NAME=clang
#        - CXX=clang++-3.8
#        - CC=clang-3.8
#      dist: trusty
#      addons:
#        apt:
#          packages:
#            - clang-3.8
#            - cmake
#            - cmake-data
#            - python3
#            - python
#          sources: *sources

script:
  - ./etc/travis_build.sh
